add_test( [==[Cache of 0-arg function]==] /home/otdel412/Desktop/AMS/Mushroom/mushroom/build/Desktop-Release/libKriging/tests/CacheTest [==[Cache of 0-arg function]==]  )
set_tests_properties( [==[Cache of 0-arg function]==] PROPERTIES WORKING_DIRECTORY /home/otdel412/Desktop/AMS/Mushroom/mushroom/build/Desktop-Release/libKriging/tests)
add_test( [==[Cache of 1-arg function]==] /home/otdel412/Desktop/AMS/Mushroom/mushroom/build/Desktop-Release/libKriging/tests/CacheTest [==[Cache of 1-arg function]==]  )
set_tests_properties( [==[Cache of 1-arg function]==] PROPERTIES WORKING_DIRECTORY /home/otdel412/Desktop/AMS/Mushroom/mushroom/build/Desktop-Release/libKriging/tests)
add_test( [==[Cache of 2-args function]==] /home/otdel412/Desktop/AMS/Mushroom/mushroom/build/Desktop-Release/libKriging/tests/CacheTest [==[Cache of 2-args function]==]  )
set_tests_properties( [==[Cache of 2-args function]==] PROPERTIES WORKING_DIRECTORY /home/otdel412/Desktop/AMS/Mushroom/mushroom/build/Desktop-Release/libKriging/tests)
add_test( [==[Cache of 0-arg function with global context]==] /home/otdel412/Desktop/AMS/Mushroom/mushroom/build/Desktop-Release/libKriging/tests/CacheTest [==[Cache of 0-arg function with global context]==]  )
set_tests_properties( [==[Cache of 0-arg function with global context]==] PROPERTIES WORKING_DIRECTORY /home/otdel412/Desktop/AMS/Mushroom/mushroom/build/Desktop-Release/libKriging/tests)
add_test( [==[Cache of 1-arg function with global context]==] /home/otdel412/Desktop/AMS/Mushroom/mushroom/build/Desktop-Release/libKriging/tests/CacheTest [==[Cache of 1-arg function with global context]==]  )
set_tests_properties( [==[Cache of 1-arg function with global context]==] PROPERTIES WORKING_DIRECTORY /home/otdel412/Desktop/AMS/Mushroom/mushroom/build/Desktop-Release/libKriging/tests)
add_test( [==[Cache of 2-args function with global context]==] /home/otdel412/Desktop/AMS/Mushroom/mushroom/build/Desktop-Release/libKriging/tests/CacheTest [==[Cache of 2-args function with global context]==]  )
set_tests_properties( [==[Cache of 2-args function with global context]==] PROPERTIES WORKING_DIRECTORY /home/otdel412/Desktop/AMS/Mushroom/mushroom/build/Desktop-Release/libKriging/tests)
add_test( [==[Cache function behaves like std::function]==] /home/otdel412/Desktop/AMS/Mushroom/mushroom/build/Desktop-Release/libKriging/tests/CacheTest [==[Cache function behaves like std::function]==]  )
set_tests_properties( [==[Cache function behaves like std::function]==] PROPERTIES WORKING_DIRECTORY /home/otdel412/Desktop/AMS/Mushroom/mushroom/build/Desktop-Release/libKriging/tests)
set( CacheTest_TESTS [==[Cache of 0-arg function]==] [==[Cache of 1-arg function]==] [==[Cache of 2-args function]==] [==[Cache of 0-arg function with global context]==] [==[Cache of 1-arg function with global context]==] [==[Cache of 2-args function with global context]==] [==[Cache function behaves like std::function]==])
